name: frames_glitch_launcher
description: "An App Launcher for Frames by Brilliant Labs"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.34.5
  logging: ^1.3.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  simple_frame_app: ^1.6.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - packages/simple_frame_app/lua/battery.min.lua
  - packages/simple_frame_app/lua/data.min.lua
  - packages/simple_frame_app/lua/code.min.lua
  - packages/simple_frame_app/lua/plain_text.min.lua
  - packages/simple_frame_app/lua/sprite.min.lua
  - assets/frame_app.lua